Repository hubiinetwork/nahmii-sdk, pull requests merged in 2018-09, with the labels that each got.

#3 Feature/hash object
  Docs/monetary-amount.md
  Docs/payment.md
  Docs/receipt.md
  Docs/utils.md
  README.md
  index.js
  lib/monetary-amount.js
  lib/monetary-amount.spec.js
  lib/payment.js
  lib/payment.spec.js
  lib/receipt.js
  lib/receipt.spec.js
  lib/striim-provider.js
  lib/utils.js
  lib/utils.spec.js
  package.json
Labels: enhancement

#8 Feature/rebranding
  Docs/monetary-amount.md
  Docs/nahmii-provider.md
  Docs/payment.md
  Docs/receipt.md
  Docs/striim-provider.md
  Docs/utils.md
  Docs/wallet.md
  README.md
  index.js
  lib/abis/ClientFund.json
  lib/monetary-amount.js
  lib/nahmii-provider.js
  lib/nahmii-provider.spec.js
  lib/nahmii-request.js
  lib/nahmii-request.spec.js
  lib/payment.js
  lib/receipt.js
  lib/utils.js
  lib/wallet.js
  lib/wallet.spec.js
  package.json
Labels: branding

#9 Update to new signature of DepositTokens() in ClientFund
  lib/wallet.js
  lib/wallet.spec.js
  package.json
Labels: bug

#10 Fix show balance command in the CLI
  lib/wallet.js
  lib/wallet.spec.js
Labels: bug

#14 Updates to support new payment engine
  Docs/nahmii-provider.md
  Docs/receipt.md
  lib/nahmii-provider.js
  lib/nahmii-provider.spec.js
  lib/receipt.js
  lib/receipt.spec.js
  package.json
Labels: enhancement
