Repository hubiinetwork/nahmii-sdk, pull requests merged in 2019-07, with the labels that each got.

#114 cleanup dependencies and add bson as peer dependency
  package.json
Labels: escalating risk

#115 Fix wallet nonce comparison
  lib/settlement/driip-settlement.js
  lib/settlement/driip-settlement.spec.js
  package.json
Labels: bug

#116 Lazy instantiation
  lib/wallet/wallet.js
  package.json
Labels: enhancement, escalating risk

#117 NahmiiProvider#operatorAddress
  Docs/nahmii-provider.md
  README.md
  lib/nahmii-provider.js
  lib/nahmii-provider.spec.js
  package.json
Labels: enhancement
