Repository hubiinetwork/nahmii-sdk, pull requests merged in 2019-04, with the labels that each got.

#89 Keep connections alive
  lib/nahmii-request.js
  package.json
Labels: technical-debt

#92 Feature/amount available
  Docs/driip-settlement.md
  Docs/settlement.md
  Docs/wallet.md
  lib/settlement/settlement.js
  lib/settlement/settlement.spec.js
  lib/wallet/wallet.js
  lib/wallet/wallet.spec.js
  package.json
Labels: enhancement

#95 nahmii contract abstractions update for mainnet
  lib/settlement/driip-settlement-challenge-contract.js
  lib/settlement/driip-settlement-contract.js
  lib/settlement/null-settlement-challenge-contract.js
  lib/settlement/null-settlement-contract.js
  package.json
Labels: WIP, enhancement
