Repository hubiinetwork/nahmii-sdk, pull requests merged in 2019-01, with the labels that each got.

#68 Feature/mainnet
  Docs/wallet.md
  lib/payment.spec.js
  lib/receipt.spec.js
  lib/settlement.spec.js
  lib/wallet/abis/erc20.json
  lib/wallet/abis/homestead/BalanceTracker.json
  lib/wallet/abis/homestead/ClientFund.json
  lib/wallet/abis/ropsten/BalanceTracker.json
  lib/wallet/abis/ropsten/ClientFund.json
  lib/wallet/balance-tracker-contract.js
  lib/wallet/balance-tracker-contract.spec.js
  lib/wallet/client-fund-contract.js
  lib/wallet/client-fund-contract.spec.js
  lib/wallet/erc20-contract.js
  lib/wallet/index.js
  lib/wallet/wallet.js
  lib/wallet/wallet.spec.js
  package.json
Labels: enhancement

#69 Feature/abi update
  lib/abis/DriipSettlement.json
  lib/abis/DriipSettlementChallenge.json
  lib/abis/NullSettlement.json
  lib/abis/NullSettlementChallenge.json
  lib/wallet/abis/ropsten/BalanceTracker.json
  lib/wallet/abis/ropsten/ClientFund.json
  package.json
Labels: enhancement

#70 Improve out-of-the-box compatibility with webpack projects
  lib/driip-settlement-challenge-contract.js
  lib/driip-settlement-contract.js
  lib/null-settlement-challenge-contract.js
  lib/null-settlement-contract.js
  lib/wallet/balance-tracker-contract.js
  lib/wallet/client-fund-contract.js
  lib/wallet/erc20-contract.js
  package.json
Labels: technical-debt

#73 Feature/erc20 allowance
  .nycrc
  Docs/erc20-contract.md
  Docs/nahmii-provider.md
  Docs/wallet.md
  README.md
  index.js
  lib/erc20/abis/erc20.json
  lib/erc20/erc20-contract.js
  lib/erc20/erx20-contract.spec.js
  lib/nahmii-provider.js
  lib/nahmii-provider.spec.js
  lib/wallet/erc20-contract.js
  lib/wallet/wallet.js
  lib/wallet/wallet.spec.js
  package.json
Labels: enhancement

#75 Remove uncatchable error, instead log it to console
  lib/nahmii-provider.js
  package.json
Labels: bug

#63 Fixes on the settlement related operations
  Docs/driip-settlement.md
  Docs/null-settlement.md
  Docs/settlement.md
  Docs/wallet.md
  index.js
  lib/driip-settlement.spec.js
  lib/nested-error.js
  lib/nested-error.spec.js
  lib/null-settlement.spec.js
  lib/settlement.js
  lib/settlement/abis/ropsten/DriipSettlement.json
  lib/settlement/abis/ropsten/DriipSettlementChallenge.json
  lib/settlement/abis/ropsten/NullSettlement.json
  lib/settlement/abis/ropsten/NullSettlementChallenge.json
  lib/settlement/driip-settlement-challenge-contract.js
  lib/settlement/driip-settlement-challenge-contract.spec.js
  lib/settlement/driip-settlement-contract.js
  lib/settlement/driip-settlement-contract.spec.js
  lib/settlement/driip-settlement.js
  lib/settlement/driip-settlement.spec.js
  lib/settlement/index.js
  lib/settlement/null-settlement-challenge-contract.js
  lib/settlement/null-settlement-challenge-contract.spec.js
  lib/settlement/null-settlement-contract.js
  lib/settlement/null-settlement-contract.spec.js
  lib/settlement/null-settlement.js
  lib/settlement/null-settlement.spec.js
  lib/settlement/settlement.js
  lib/settlement/settlement.spec.js
  lib/settlement/utils.js
  lib/wallet/wallet.js
  lib/wallet/wallet.spec.js
  package.json
Labels: bug, enhancement

#79 Updated contracts to prerelease 9 (pre-9)
  Docs/null-settlement.md
  lib/settlement/abis/ropsten/DriipSettlement.json
  lib/settlement/abis/ropsten/DriipSettlementChallenge.json
  lib/settlement/abis/ropsten/NullSettlement.json
  lib/settlement/abis/ropsten/NullSettlementChallenge.json
  lib/settlement/null-settlement.js
  lib/settlement/null-settlement.spec.js
  lib/wallet/abis/ropsten/BalanceTracker.json
  lib/wallet/abis/ropsten/ClientFund.json
  package.json
Labels: enhancement
